title: "standard_python_environment"
description: "Python environment built with **Docker Compose"
baseurl: "/standard_python_environment"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge